spring:
  application:
    name: cardapio-backend

  # Configuração do Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5432/cardapio_pro
    username: cardapio
    password: cardapio123

  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true